from __future__ import annotations

from klipperai_agent.config.requests import ConfigPromptPayload
from klipperai_agent.domain.proposals import ConfigProposal


class MacroProposal:
    def build(self, payload: ConfigPromptPayload, warnings: list[str]) -> ConfigProposal:
        return ConfigProposal(
            feature="macro",
            title="Starter gcode macro",
            target_file="klipperai/macros.cfg",
            config=(
                "[gcode_macro CUSTOM_ACTION]\n"
                "description: Starter macro generated by KlipperAI\n"
                "gcode:\n"
                '  RESPOND MSG="Replace this body with your real macro steps"\n'
            ),
            rationale="A minimal macro stub gives you the correct structure for a new Klipper macro while keeping the logic easy to replace.",
            assumptions=[
                "You want a new macro scaffold rather than edits to an existing macro.",
            ],
            warnings=warnings,
        )


class FilamentProposal:
    def build(self, payload: ConfigPromptPayload, warnings: list[str]) -> ConfigProposal:
        assumptions = [
            "The sensor is a basic switch-style runout detector.",
        ]
        if payload.profile.filament_sensor == "motion":
            warnings.append(
                "The saved printer profile already indicates a motion-style filament sensor. A switch-sensor scaffold may not match your current hardware."
            )
        elif payload.profile.filament_sensor == "switch":
            warnings.append(
                "The saved printer profile already indicates a switch-style filament sensor. Review overlap before adding another runout section."
            )
        elif payload.profile.filament_sensor == "none":
            assumptions.append(
                "The saved printer profile currently shows no filament sensor configured."
            )
        return ConfigProposal(
            feature="filament",
            title="Starter filament runout sensor section",
            target_file="klipperai/filament.cfg",
            config=(
                "[filament_switch_sensor runout]\n"
                "switch_pin: <SWITCH_PIN>\n"
                "pause_on_runout: True\n"
                "runout_gcode:\n"
                "  PAUSE\n"
            ),
            rationale="This is a safe baseline for a simple filament switch sensor that pauses on runout.",
            assumptions=assumptions,
            warnings=["Replace <SWITCH_PIN> with the actual sensor input pin.", *warnings],
        )


class GenericProposal:
    def build(self, payload: ConfigPromptPayload, warnings: list[str]) -> ConfigProposal:
        feature_slug = payload.target.feature if payload.target.feature != "generic" else "custom"
        return ConfigProposal(
            feature=payload.target.feature,
            title="Generic managed include scaffold",
            target_file=f"klipperai/{feature_slug}.cfg",
            config=(
                "# Replace this scaffold with the exact Klipper sections you want.\n"
                f"# Request target detected as: {payload.target.feature}\n"
                "[section_name_here]\n"
                "option_name: <VALUE>\n"
            ),
            rationale="This generic scaffold formats the request as a managed include snippet even when the local stub provider cannot infer a more precise built-in template.",
            assumptions=[
                "The request did not map cleanly to a more specific built-in template.",
            ],
            warnings=["Replace the placeholder section and option names before use.", *warnings],
        )
